-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaMtcAJ6F+ng0XcGd
WRmZXz2teJHjTdADCniIGQg3En6gCgYIKoZIzj0DAQehRANCAARegfzAfcim9PBC
0pDCMF+BaaNYqzR9lC6Zh/cvMYviJz4IfvurKGoQJ0ttI1jkJY26nNdz4e7CrTTH
g0Jlt5aF
-----END PRIVATE KEY-----