-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkHwreLS3mqEEnbk3
jnNV39vlH9tU8Yq4gHlWhutlq+KgCgYIKoZIzj0DAQehRANCAARHe9tGrtABE10Y
LNOG8mglbd0UOfMNk+TpJEbIQAN1wLvHrL8OyQVI/tCsQY38igs8Yok+KGD9jR7W
tMAVMgIC
-----END PRIVATE KEY-----